export const SITE = Object.freeze({
    name: 'Simsang Archive',
    shortName: 'Simsang',
    title: 'Simsang Archive | Premium Knowledge Portal',
    description: 'A premium archive of astrology, yoga, the Gita, Bardo wisdom, and Samshin doctrine.',
    url: 'https://simsang.org',
    canonicalUrl: 'https://simsang.org/',
    locale: 'ko_KR',
    themeColor: '#f8f4eb',
    backgroundColor: '#ffffff',
    ogImageUrl: 'https://simsang.org/og-image.jpg',
    robotsPath: '/robots.txt',
    sitemapPath: '/sitemap.xml',
    manifestPath: '/manifest.json',
});
